const api = {
    home: {path: '/',name: 'home'},
    order: {path:'/orders', name: 'order'},
    product: {path: '/product',name: 'product'},
    orderDetail: {path: '/order/details', name : 'order detail'},
    search: {path:'/search', name: 'search'},
    profile: {path: '/profile', name: 'profile'},
    profileEdit: {path: '/profileEdit', name: 'profileEdit'},
    blacklist: {path: '/blacklist', name: 'blacklist'},
    productDetails: {path: '/product/detail', name: 'product detail'},
    addProduct: {path: '/product/add', name: 'add product'},
    updateGoods: {path: '/product/update', name: 'update product'},
    receipt: {path: '/receipt', name: 'receipt'},
    productComments: {path: '/product/comments', name: 'product comments'},
    shoppingCart: {path: '/shoppingCart', name: 'shopping card'},
    purchase: {path: '/purchase', name: 'purchase'},
    shop: {path: '/shop', name: 'shop'},
    login: {path: '/login', name: 'login'},
    register: {path: '/register', name: 'register'},
    reSetPassword: {path: '/reset/password', name: 'reSetPassword'},
}

export const netApi = {
    login:{path: '/shop/login', },
    register:{path: '/shop/register', },
    info:{path: '/user/info', },
    shopInfo: {path: 'shop/'},
    update: [
        {name: 'account',path: '/user/update/account'},
        {name: 'nickname',path: '/user/update/nickname'},
        {name: 'password',path: '/user/update/password'},
        {name: 'avatar',path: '/user/update/avatar'},
        {name: 'email',path: '/user/update/email'},
        {name: 'userPhone', path: '/user/update/phone'},

        {name: 'shopPhone', path: '/shop/update/phone'},
        {name: 'shopName', path: '/shop/update/shopName'},
        {name: 'location', path: '/shop/update/location'},
        {name: 'shopLogo',path: '/shop/update/ShopLogo'},

    ],
    reSetPassword: {path: 'user/rest/password'},
    recommend: {path: '/product/recommend/'},
    location: {path: 'shop/location'},
    getSaleProduct: {path: '/product/get/sale/'},
    getProduct: {path: '/product/get/'},
    getAnyProduct: {path: '/product/get/'},
    productPicture: {path: 'product/picture/list/'},
    productSpecs: {path: 'product/get/specs/'},
    productComments: {path: 'product/comments/'},
    getPrice: {path: 'product/get/price'},
    shopShowInfo: {path: 'shop/'},
    saleProduct: {path: 'shop/sale/'},
    getOrder: {path: 'product/payment/order'},
    getOrderDetail: {path: 'order/detail/'},
    addCart: {path: 'cart/add'},
    getCart: {path: 'cart/get'},
    removeFromCart: {path: 'cart/remove'},
    orderInfo: {path: 'order/shop/info/'},
    orderCancel : {path: 'order/cancel'},
    orderFinish: {path: 'order/finish'},
    getGoods: {path: 'shop/get/goods'},
    getSaleGoods: {path:'shop/get/goods/sale'},
    getUnSaleGoods: {path:'shop/get/goods/unSale'},

    updateState: {path: 'shop/update/status'},
    shopStatus: {path: '/shop/get/businessStatus'},
    updateSaleStatus: {path: 'product/update/list/saleStatus'},
    getCategory: {path: '/product/get/category'},
    addGoods: {path: 'shop/add/goods'},
    updateGoods: {path: 'product/update/goods'},
    deleteGoods: {path: 'product/delete'},
    searchGoods: {path: 'shop/search/'},
    updateGoodsSaleStatus: {path: 'product/update/saleStatus'},
}
export default api